server:
  port: 8080

spring:
  application:
    name: casocitasmedicas

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  cloud:
    consul:
      config:
        enabled: true
        import-check:
          enabled: false
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        enabled: true
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
